### ISSUE TITLE
Dev Portal - 3Box Integration

### ISSUE THREAD

**Issue by ryanchristo** [JoinColony/JoinColony.github.io#105]
## Description

We received a request from one of our users to integrate [3Box](https://3box.io/) so that users can share their profile information across Ethereum accounts. I spent some time looking into 3Box this past weekend and I think it would be worth investigating further.

3Box is built with OrbitDB and is currently offering three APIs: Profile, Messaging, and Storage. I think it would be worth exploring both the Profile and Storage APIs.

**Comment by ceolson01** [comment]
Closing, as the dev portal will no longer be supported.
