### ISSUE TITLE
"Get in touch" form should post to Discord webhook

### ISSUE THREAD

**Issue by auryn-macmillan** [JoinColony/JoinColony.github.io#148]
We're shutting down HubSpot, so for the time being, I'd like to post the responses to "get in touch" form to a new private discord channel via a discord webhook.
![Screenshot from 2020-06-18 16-41-22@2x](https://user-images.githubusercontent.com/8453294/85069722-9ad90480-b182-11ea-97e0-0e79a4c8fd13.png)
![Screenshot from 2020-06-18 16-41-32@2x](https://user-images.githubusercontent.com/8453294/85069725-9c0a3180-b182-11ea-891e-5859d84fe555.png)

Here is the Discord webhook documentation.
https://discord.com/developers/docs/resources/webhook#execute-webhook-jsonform-params

DM me for webhook details, or feel free to create a new one yourself.

**Comment by rdig** [comment]
@ceolson01 I see you're assigned to this, are you also currently working on it?

I'm pushing an update to the website, then want to push it into production as soon as possible, so I wanted to know if we can get this is as well.

**Comment by ceolson01** [comment]
I'm beginning work on this today
