### ISSUE TITLE
Dev Portal - Homepage for each section

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/JoinColony.github.io#60]
The current docs site does not support a homepage for each section header, e.g. "Docs", "Interface" etc. Instead, currently half of the sections have an "Overview" page that serves that purpose to an extent. The problem is that an "Overview" type page when navigated to, drills the left hand navigation down to itself which is counter intuitive when linked across from somewhere else. As an example, if we want to link to the docs section we have to use a link to the "Overview" page where the left hand navigation gives little to understand where we've ended up https://docs.colony.io/colonynetwork/docs-overview

Having section homepages also enforces overview content and provides link-ability to that section.

**Comment by ceolson01** [comment]
Closing, as the dev portal will no longer be supported.
