### ISSUE TITLE
Dev Portal - Optimize use of hooks

### ISSUE THREAD

**Issue by ryanchristo** [JoinColony/JoinColony.github.io#73]
## Description

We currently have the hooks that are implemented on the `layout` level. We should create a `hooks` directory that will house reusable hooks and implement those hooks only on the pages where the hooks are required to improve performance.

The `useMetaMask` hook currently applies to all pages within the developer portal in order to display the network in the top navigation but this hook is the most demanding. It would be nice to find a solution to prevent the event listeners while viewing the documentation.

**Comment by ceolson01** [comment]
Closing, as the dev portal will no longer be supported.
