### ISSUE TITLE
Dev Portal - Add service layer and use axios

### ISSUE THREAD

**Issue by ryanchristo** [JoinColony/JoinColony.github.io#74]
## Description

We should make a simple API wrapper or service layer and use `axios` instead of `fetch` to fetch resources from GitHub and the portal server.

See comments https://github.com/JoinColony/JoinColony.github.io/pull/56#discussion_r283495468 and https://github.com/JoinColony/JoinColony.github.io/pull/63#discussion_r293958701.

**Comment by ceolson01** [comment]
Closing, as the dev portal will no longer be supported.
