### ISSUE TITLE
Dev Portal - Add task and payment modals

### ISSUE THREAD

**Issue by ryanchristo** [JoinColony/JoinColony.github.io#77]
## Description

Currently we have a page for viewing a task and a page for viewing a payment. @itspatch has provided designs for the use of modals instead of these pages.

<img width="1021" alt="Screen Shot 2019-06-28 at 5 06 48 PM" src="https://user-images.githubusercontent.com/12519942/60335079-2e8c5080-99c7-11e9-85b8-2588fa536db4.png">

<img width="1023" alt="Screen Shot 2019-06-28 at 5 07 03 PM" src="https://user-images.githubusercontent.com/12519942/60335090-31874100-99c7-11e9-98a8-206686b25c6a.png">

See [figma designs](https://www.figma.com/file/INjVpzQUquI7PpARotabBHf6/Contribute?node-id=229%3A0) and comment https://github.com/JoinColony/JoinColony.github.io/pull/65#discussion_r296311049.

**Comment by ceolson01** [comment]
Closing, as the dev portal will no longer be supported.
