### ISSUE TITLE
New Website

### ISSUE THREAD

**Issue by ceolson01** [JoinColony/JoinColony.github.io#92]
This issue serves as an Epic to track website progress

**Comment by NeoBeum** [comment]
Are these two sites able to communicate? 
JoinColony.github.io 
colony.io/colony

**Comment by ceolson01** [comment]
Hey @NeoBeum!

Currently, [JoinColony.github.io](https://github.com/JoinColony/JoinColony.github.io) and the Colony Dapp (`colony.io/colony/*`) are two separate projects, and don't communicate with one another.
