### ISSUE TITLE
Dev Portal - Update expanded link social image

### ISSUE THREAD

**Issue by ryanchristo** [JoinColony/JoinColony.github.io#97]
## Description

It looks like one of the social images has not been updated from our old logo:

<img width="711" alt="Screen Shot 2019-07-22 at 10 17 05 AM" src="https://user-images.githubusercontent.com/12519942/61617093-51c6ba80-ac6a-11e9-9e8b-16b79065d290.png">

We need to fix this!

**Comment by ceolson01** [comment]
Closing, as the dev portal will no longer be supported.
